import { MILLISECOND } from '../constants.js';

const GAME_SETTING = Object.freeze({
  ADVANCE_NUMBER: 4,
  ADVANCE_RANGE_MIN: 0,
  ADVANCE_RANGE_MAX: 9,
  DISTANCE_NUMBER: 1,
  CAR_NAME_LENGTH_MIN: 1,
  CAR_NAME_LENGTH_MAX: 5,
  ROUND_INTERVAL: 1 * MILLISECOND,
});

export default GAME_SETTING;
