const CONFIG = Object.freeze({
  INITIAL_NUMBER: 0,
  MINIMUM_ATTEMPTS_NUMBER: 0,
  MINIMUM_RANDOM_NUMBER: 4,
  MAXIMUM_RANDOM_NUMBER: 9,
  MINIMUM_CAR_NAME: 1,
  MAXIMUM_CAR_NAME: 5,
  COMMA: ',',
  RACE_STEP: '-',
  BLANK: ' ',
  LINE_BREAK: '\n',
});

export {
  CONFIG,
};
