const MINIMUM_RANDOM_NUMBER_TO_MOVE = 4;
const MAX_CARNAME_LENGTH = 5;
const RANDOM_LOWER_INCLUSIVE = 1;
const RANDOM_UPPER_INCLUSIVE = 8;

module.exports = {
  MINIMUM_RANDOM_NUMBER_TO_MOVE,
  MAX_CARNAME_LENGTH,
  RANDOM_LOWER_INCLUSIVE,
  RANDOM_UPPER_INCLUSIVE,
};
