export const NUMBER = Object.freeze({
  MIN_CAR_NAME_LENGTH: 1,
  MAX_CAR_NAME_LENGTH: 5,
  MIN_CAR_LIST_LENGTH: 2,
  MAX_CAR_LIST_LENGTH: 100,
  MOVE_POSITION: 1,
  INIT_POSITION: 0,
  MIN_NUMBER_TO_MOVE: 4,
  MIN_TRY_COUNT: 1,
});
