const numeric = Object.freeze({
  CAR_NAME_LENGTH_LOWER: 1,
  CAR_NAME_LENGTH_UPPER: 5,
  RANDOM_NUMBER_LOWER: 0,
  RANDOM_NUMBER_UPPER: 9,
  MOVE_STANDARD: 4,
  MOVE_DISTANCE: 1,

  MIN_MAX_TRY_COUNT: 1,
  MAX_MAX_TRY_COUNT: 100,
});

export default numeric;
