const CAR_RULE = {
  INIT_DISTANCE: 1,
  MIN_NAME_LENGTH: 1,
  MAX_NAME_LENGTH: 5,
  NAME_SEPARATOR: ',',
};

const GAME_RULE = {
  RANDOM_NUMBER_RANGE_START: 0,
  RANDOM_NUMBER_RANGE_END: 9,
  MOVING_CONDITION: 4,
};

module.exports = { CAR_RULE, GAME_RULE };
