const CONSTANTS = {
  COMMA: ',',
  DEFAULT_POSTION: 0,
  LOWER_NUMBER: 0,
  UPPER_NUMBER: 10,
  MIN_NUMBER_OF_MOVING: 4,
  MIN_NUMBER_OF_NAMES: 2,
  MAX_NAME_LENGTH: 5,
  EMPTY: '',
  COLON: ':',
  DASH: '-',
  DELIMITER: ', ',
  UNDEFINED_TYPE: 'undefined',
};

module.exports = CONSTANTS;
