const MAX_NAME_LENGTH = 5;
const SCROLL_PREVENT_LENGTH = 9;
const MAX_SUBMITABLE_COUNT = 20000;
const COUNT_CLICKED_ELEMENT_LENGTH = 2;

const ALREADY_NAME_SUBMITTED_ALERT = "이미 이름이 등록되었습니다.";
const INCLUDE_BLANK_NAME_ALERT = "빈 문자인 이름은 등록할 수 없습니다.";
const OVER_SCROLL_PREVENT_ALERT = "가로 스크롤 생성을 방지하기 위해 이름 등록은 9개 이하로 제한하고 있습니다.";
const HAVE_NAME_OVER_MAX_LENGTH_ALERT = "5자를 넘는 이름은 등록할 수 없습니다.";
const DUPLIACTED_NAME_ALERT = "중복된 이름은 등록할 수 없습니다.";

const ALREADY_COUNT_SUBMITTED_ALERT = "이미 횟수를 설정하였습니다.";
const INVALID_INTEGER_ALERT = "자연수만 설정할 수 있습니다.";
const OVER_MAX_COUNT_ALERT = "원활한 게임을 위해 횟수는 20000 이하로 제한하고 있습니다.";

export {
	MAX_NAME_LENGTH,
	SCROLL_PREVENT_LENGTH,
	MAX_SUBMITABLE_COUNT,
	COUNT_CLICKED_ELEMENT_LENGTH,
	ALREADY_NAME_SUBMITTED_ALERT,
	INCLUDE_BLANK_NAME_ALERT,
	OVER_SCROLL_PREVENT_ALERT,
	HAVE_NAME_OVER_MAX_LENGTH_ALERT,
	DUPLIACTED_NAME_ALERT,
	ALREADY_COUNT_SUBMITTED_ALERT,
	INVALID_INTEGER_ALERT,
	OVER_MAX_COUNT_ALERT,
};
