const LEGAL_CAR_NAME = '준,포코,공원,제이슨,포비';
const ILLEGAL_LENGTH_NAMES = ['준,,', '포비,준포코공원제이슨'];
const DUPLICATED_NAME = '준,준';
const SINGLE_NAME = '공원';

const MIN_RACINGCOUNT = 1;
const MAX_RACINGCOUNT = 1000;

export {
  LEGAL_CAR_NAME,
  ILLEGAL_LENGTH_NAMES,
  DUPLICATED_NAME,
  SINGLE_NAME,
  MIN_RACINGCOUNT,
  MAX_RACINGCOUNT,
};
