const NUMBERS = Object.freeze({
  MIN_NAME_LENGTH: 1,
  MAX_NAME_LENGTH: 5,
  MAX_RACE_TIME: 10,
  LESS_THEN_MIN_ROUND: 0,
  MORE_THEN_MAX_ROUND: 101,
  VALID_RACE_TIME: 3,
  VALID_RACE_PROGRESS_TIME: 3000,
  ENTIRE_NUMBER: 9,
  MOVABLE_NUMBER: 4,
  PROCESS_ROUND_TIME: 1000,
  ALERT_DISPLAY_TIME: 2000,
});

export default NUMBERS;
